project:
  type: book

book:
  title: "Hands-On Geospatial AI for Environmental Applications"
  author: "Pratyush Tripathy"
  chapters:
    - index.qmd
    - chapters/01-getting-started.qmd
    - chapters/02-gis-basics.ipynb

format:
  html:
    toc: true
    toc-location: left
    code-fold: true
    output-dir: "_site" 

execute:
  echo: true
  warning: false
  error: false
