project:
  type: book

book:
  title: "Hands-On Geospatial AI for Environmental Applications"
  author: "Pratyush Tripathy"
  chapters:
    - index.qmd
    - intro.qmd
    - chapters/01-getting-started.qmd
    - chapters/02-gis-basics.ipynb

format:
  html:
    toc: true
    toc-location: left
    toc-numbered: false
    code-fold: false
    number-sections: false
    output-dir: "docs" 

execute:
  echo: true
  warning: false
  error: false
